#!/usr/bin/env python3
"""Export the complete reconstructable teacher prompt bundle for the GLEAM failure case."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from procurement_graph.reasoning.schema_retrieval import retrieve_schema_context  # noqa: E402
from procurement_graph.reasoning.typed_planning import (  # noqa: E402
    compile_typed_plan,
    graph_plan_schema,
    intent_program_schema,
    question_intent_program_messages,
    repair_graph_plan_schema,
    repair_understanding_messages,
    typed_replan_messages,
)


CASE_ID = "L2::bridge_join_0583#L2a"


def read_case(path: Path) -> dict[str, Any]:
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if str(row.get("id")) == CASE_ID:
            return row
    raise KeyError(f"{CASE_ID} not found in {path}")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    benchmark_path = ROOT / "data/qa/cicada_core_v4/train.jsonl"
    trace_path = ROOT / "data/qa/teacher_full_v1/traces.jsonl"
    hard_path = ROOT / "data/qa/teacher_full_v1/hard_negatives.jsonl"
    repair_path = ROOT / "data/qa/teacher_full_v1/repair_sft.jsonl"
    dpo_path = ROOT / "data/qa/teacher_full_v1/dpo_pairs.jsonl"
    prompt_source = ROOT / "src/procurement_graph/reasoning/typed_planning.py"
    feedback_source = ROOT / "scripts/eval_targeted_v2.py"

    benchmark = read_case(benchmark_path)
    trace = read_case(trace_path)
    hard = read_case(hard_path)
    repair = read_case(repair_path)
    dpo = read_case(dpo_path)
    question = str(benchmark["question"])
    briefing = hard["step1_briefing"]
    rejected = hard["rejected_graph_plan"]
    accepted = repair["target_graph_plan"]
    schema_context = retrieve_schema_context(question)

    stage1_system, stage1_user = question_intent_program_messages(
        question, schema_context=schema_context
    )
    compiled = compile_typed_plan(question, {"intent_program": briefing})
    compiled_graph = getattr(getattr(compiled, "graph_plan", None), "raw_graph_plan", None)

    allowed_actions = [
        "fix_question_type",
        "repair_constraints",
        "swap_buyer_supplier",
        "change_operator",
        "change_operation",
        "abstain",
    ]
    full_repair_feedback = {
        "question": question,
        "selected_plan_id": getattr(compiled, "plan_id", "intent:p0"),
        "failed_plan": {"graph_plan": rejected},
        "failure_stage": "verifier",
        "failure_reason": "wrong_answer",
        "submitted_answer": hard["answer"],
        "grounding_issues": [],
        "schema_errors": [],
        "failed_checks": [],
        "answer_sanity": {},
        "postflight_failed_checks": [],
        "deterministic_guards_added": [],
        "allowed_repair_actions": allowed_actions,
        "notes": [
            "The submitted answer did not match the hidden verifier.",
            "The reference/oracle answer is intentionally hidden from the reflector.",
            "Repair the plan using only the question and trace summary.",
        ],
    }
    reading_system, reading_user = repair_understanding_messages(
        question, full_repair_feedback
    )

    # The original repair-reading completion was discarded by run_teacher.py.  This graph-repair
    # prompt is the complete prompt generated from all preserved fields, with no invented
    # repair_understanding.  The bundle labels that boundary explicitly.
    graph_feedback = {
        **full_repair_feedback,
        "retrieved_schema_context": schema_context,
    }
    graph_system, graph_user = typed_replan_messages(question, graph_feedback)

    bundle = {
        "case_id": CASE_ID,
        "question": question,
        "provenance_notice": {
            "historical_fact": (
                "The compact historical artifacts preserve the parsed Stage-1 output, rejected "
                "graph, submitted answer, accepted repair, and oracle decision. They do not "
                "preserve the original API request bytes or the repair-reading completion."
            ),
            "reconstruction_rule": (
                "System messages, user messages, and response schemas below are regenerated by "
                "the committed prompt builders using the stored question and case fields."
            ),
            "initial_route": (
                "The current deterministic intent compiler maps the stored Stage-1 output to a "
                "graph exactly equal to the historical rejected graph. Consequently no initial "
                "Stage-2 LLM prompt is attributed to this case."
            ),
            "repair_boundary": (
                "The full repair-reading input can be reconstructed. Its model completion was not "
                "stored, so the exact subsequent historical graph-repair user message cannot be "
                "recovered byte for byte. A complete no-invention reconstruction from preserved "
                "fields is included and labelled accordingly."
            ),
        },
        "models_and_routing": {
            "stage1_model": "gpt-5.4-nano",
            "configured_plan_and_repair_model": "grok-4-1-fast-non-reasoning",
            "teacher_temperature": 0.0,
            "configured_plan_samples": 2,
            "initial_graph_route": "deterministic_intent_compiler",
            "initial_stage2_llm_called": False,
            "initial_compilation_equals_historical_rejected_graph": compiled_graph == rejected,
        },
        "initial_teacher_call_stage1": {
            "evidence_status": "prompt reconstructed exactly by committed builder",
            "model": "gpt-5.4-nano",
            "temperature": 0.0,
            "messages": [
                {"role": "system", "content": stage1_system},
                {"role": "user", "content": stage1_user},
            ],
            "response_format": {
                "type": "json_schema",
                "json_schema": intent_program_schema(),
            },
            "historical_parsed_response": briefing,
        },
        "deterministic_initial_compilation": {
            "compiled_graph": compiled_graph,
            "historical_rejected_graph": rejected,
            "equal": compiled_graph == rejected,
            "historical_execution_answer": trace["answer"],
            "historical_online_verified": trace["verified"],
            "historical_oracle_match": trace["oracle_match"],
            "hidden_oracle_for_offline_evaluation_only": trace["oracle"],
        },
        "repair_teacher_call_1_reading": {
            "evidence_status": (
                "complete prompt reconstructed from committed builder and preserved failure fields"
            ),
            "model": "gpt-5.4-nano",
            "temperature": 0.0,
            "messages": [
                {"role": "system", "content": reading_system},
                {"role": "user", "content": reading_user},
            ],
            "response_format": "free text with eight labelled sections",
            "historical_model_response": None,
            "missing_reason": "run_teacher.py did not export the repair-reading completion",
        },
        "repair_teacher_call_2_graph": {
            "evidence_status": (
                "complete no-invention reconstruction from preserved fields; the historical "
                "prompt additionally contained the discarded repair-reading completion"
            ),
            "model": "grok-4-1-fast-non-reasoning",
            "temperature": 0.0,
            "messages": [
                {"role": "system", "content": graph_system},
                {"role": "user", "content": graph_user},
            ],
            "response_format": {
                "type": "json_schema",
                "json_schema": repair_graph_plan_schema("optional"),
            },
            "historical_accepted_repaired_graph": accepted,
        },
        "configured_stage2_schema_not_used_on_initial_fast_path": {
            "response_format": {
                "type": "json_schema",
                "json_schema": graph_plan_schema("optional"),
            }
        },
        "stored_compact_training_view": {
            "failure_feedback": repair["failure_feedback"],
            "chosen_graph_plan": dpo["chosen_graph_plan"],
            "rejected_graph_plan": dpo["rejected_graph_plan"],
        },
        "source_hashes": {
            str(benchmark_path.relative_to(ROOT)): sha256(benchmark_path),
            str(trace_path.relative_to(ROOT)): sha256(trace_path),
            str(hard_path.relative_to(ROOT)): sha256(hard_path),
            str(repair_path.relative_to(ROOT)): sha256(repair_path),
            str(dpo_path.relative_to(ROOT)): sha256(dpo_path),
            str(prompt_source.relative_to(ROOT)): sha256(prompt_source),
            str(feedback_source.relative_to(ROOT)): sha256(feedback_source),
        },
    }

    out_dir = ROOT / "paper/tmlr_v4"
    json_path = out_dir / "gleam_teacher_prompt_bundle.json"
    txt_path = out_dir / "gleam_teacher_prompt_bundle.txt"
    json_text = json.dumps(bundle, ensure_ascii=False, indent=2)
    json_path.write_text(json_text + "\n", encoding="utf-8")

    sections = [
        "GLEAM COMPLETE TEACHER PROMPT BUNDLE",
        "=" * 80,
        json.dumps(bundle["provenance_notice"], ensure_ascii=False, indent=2),
        "\nINITIAL TEACHER CALL: STAGE 1 SYSTEM\n" + "-" * 80,
        stage1_system,
        "\nINITIAL TEACHER CALL: STAGE 1 USER\n" + "-" * 80,
        stage1_user,
        "\nINITIAL TEACHER CALL: RESPONSE FORMAT\n" + "-" * 80,
        json.dumps(bundle["initial_teacher_call_stage1"]["response_format"],
                   ensure_ascii=False, indent=2),
        "\nHISTORICAL STAGE 1 RESPONSE\n" + "-" * 80,
        json.dumps(briefing, ensure_ascii=False, indent=2),
        "\nDETERMINISTIC COMPILATION AND HISTORICAL RESULT\n" + "-" * 80,
        json.dumps(bundle["deterministic_initial_compilation"], ensure_ascii=False, indent=2),
        "\nREPAIR TEACHER CALL 1: SYSTEM\n" + "-" * 80,
        reading_system,
        "\nREPAIR TEACHER CALL 1: USER\n" + "-" * 80,
        reading_user,
        "\nREPAIR TEACHER CALL 2: SYSTEM\n" + "-" * 80,
        graph_system,
        "\nREPAIR TEACHER CALL 2: USER\n" + "-" * 80,
        graph_user,
        "\nREPAIR TEACHER CALL 2: RESPONSE FORMAT\n" + "-" * 80,
        json.dumps(bundle["repair_teacher_call_2_graph"]["response_format"],
                   ensure_ascii=False, indent=2),
        "\nHISTORICAL ACCEPTED REPAIR\n" + "-" * 80,
        json.dumps(accepted, ensure_ascii=False, indent=2),
    ]
    txt_path.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(json_path)
    print(txt_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
